Repository Ayu-hack/GeeksforGeeks-POTD-Solution, pull requests merged in 2024-10, with the labels that each got.

#1 Majority Vote(3 October).java
  October 2024/Majority Vote(3 October).java
Labels: enhancement, good first issue

#3 Deletion and Reverse in Circular Linked List(4 Oct).java
  October 2024/Deletion and Reverse in Circular Linked List(4 Oct).java
Labels: enhancement, good first issue

#5 Create Not a subset sum(5 oct).java
  October 2024/Not a subset sum(5 oct).java
Labels: enhancement

#7 Find the number of islands(6 Oct).java
  October 2024/Find the number of islands(6 Oct).java
Labels: enhancement

#9 XOR Linked List(7 oct).cpp
  October 2024/XOR Linked List(7 oct).cpp
Labels: enhancement

#22 Added POTD for 8 October 2024
  October 2024/Largest_pair_sum(8 Oct).cpp
Labels: hacktoberfest-accepted

#27 Added Potd solution for 27 September 2024
  September 2024/K_sized_subarray_Maximum(27 sept).cpp
Labels: hacktoberfest-accepted

#29 Added 'Total Count' Solution of GFG 29th Sept POTD
  September 2024/Total Count(29th Sept).py
Labels: hacktoberfest-accepted

#32 Added Eye Disease Classification model as py file it also contains di…
  Projects Ai-ML/Eye Disease Classified RNN/eye_disease_classified_rnn.py
Labels: hacktoberfest-accepted

#31 Add random quote picker!
  Mini Projects/Quote Picker/README.md
  Mini Projects/Quote Picker/index.html
  Mini Projects/Quote Picker/script.js
  Mini Projects/Quote Picker/style.css
Labels: hacktoberfest-accepted

#36 Added pomodaro app
  Mini Projects/pomodaro_app/README.md
  Mini Projects/pomodaro_app/main.py
  Mini Projects/pomodaro_app/tomato.png
Labels: hacktoberfest-accepted

#37 Added solution to the POTD of 14 September
  September 2024/Alternate_positive_and_negative_numbers(14 Sept).cpp
Labels: hacktoberfest-accepted

#40 Added Potd Solution for 12 September
  September 2024/Middle_of_linked_list(12 Sept).cpp
Labels: hacktoberfest-accepted

#41 Implement maxGoodNumber function to find maximum possible number by binary concatenation
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  October 2024/maximumPossibleNumberByBinaryConcatenation.cpp
Labels: good first issue, hacktoberfest-accepted

#39 Create Leetcode WC-413 September 1st KthNearestObstacleQueries.cpp
  September 2024/KthNearestObstacleQueries.cpp
Labels: good first issue, hacktoberfest-accepted

#43 Create SDL2 project on Mouse and keyboard Events
  SDL2project.cpp
Labels: good first issue, hacktoberfest-accepted

#46 Create 8-oct-potd ( java-without using sort() )
  October 2024/8-oct-potd (java-without using sort() )
Labels: good first issue, hacktoberfest-accepted

#38 Breast Cancer Classifier Web App using Streamlit
  Projects Ai-ML/Breast-Cancer-Classifier-Web-App-using-Streamlit/Benign tumour.png
  Projects Ai-ML/Breast-Cancer-Classifier-Web-App-using-Streamlit/Breast_Cancer_Classifier.ipynb
  Projects Ai-ML/Breast-Cancer-Classifier-Web-App-using-Streamlit/Breast_Cancer_Classifier.sav
  Projects Ai-ML/Breast-Cancer-Classifier-Web-App-using-Streamlit/Breast_Cancer_Classifier_Web_App.py
  Projects Ai-ML/Breast-Cancer-Classifier-Web-App-using-Streamlit/Breast_cancer_data.csv
  Projects Ai-ML/Breast-Cancer-Classifier-Web-App-using-Streamlit/Malignant Tumour.png
  Projects Ai-ML/Breast-Cancer-Classifier-Web-App-using-Streamlit/README.md
  Projects Ai-ML/Breast-Cancer-Classifier-Web-App-using-Streamlit/requirements.txt
Labels: good first issue, hacktoberfest-accepted

#48 Adding Jump Game Question Sept streak question
  September 2024/55.JumpGame
Labels: hacktoberfest-accepted

#49 Health Tool: BMI Calculator
  Mini Projects/Heath Tool BMI Calculator.py
Labels: hacktoberfest-accepted

#52 Added POTD solution for 4th September
  September 2024/Count_ways_to_N'th_Stair(4 Sept).cpp
Labels: hacktoberfest-accepted

#42 Oct 8 GFG POTD
  October 2024/Largest_pair_sum(8 Oct).cpp
Labels: good first issue, hacktoberfest-accepted

#53 Added POTD for August 28
  August 2024/Sorting_Elements_of_an_Array_by_Frequency(28 August).cpp
Labels: hacktoberfest-accepted

#55 Maximum Product : GFG - Weekly contest
  October 2024/maximumProduct.cpp
Labels: hacktoberfest-accepted

#59 Added Solution of POTD of July 1
  July 2024/01_July_POTD.cpp
  July 2024/readme.md
Labels: hacktoberfest-accepted

#61 Create Created Linked List Matrix(9th october).java
  October 2024/Created Linked List Matrix(9th october).java
Labels: good first issue, hacktoberfest-accepted

#35 Create Max sum path in two arrays(1st September).java
  September 2024/Max sum path in two arrays(1st September).java
Labels: good first issue, hacktoberfest-accepted

#65 Solved Largest Pair Sum (Oct 8) Using Python
  October 2024/Largest Pair Sum(8 Oct).py
Labels: good first issue, hacktoberfest-accepted

#67 Added Kadane's Algorithm code
  March 2024/readme.md
Labels: good first issue, hacktoberfest-accepted

#66 Create Sort (0, 1, 2).java
  September 2024/Sort (0, 1, 2).java
Labels: hacktoberfest-accepted

#64 Added Solution POTD OCT 9 using python
  October 2024/Linked List Matrix(9 oct).py
Labels: good first issue, hacktoberfest-accepted

#71 Create Check for BST (24 July).cpp
  July 2024/Check for BST (24 July).cpp
Labels: hacktoberfest-accepted

#72 Create Array Pair Sum Divisibility Problem (1 Jan).cpp
  January 2024/Array Pair Sum Divisibility Problem (1 Jan).cpp
Labels: hacktoberfest-accepted

#73 Added POTD for July 28
  July 2024/Remove_Duplicates(28 July).cpp
Labels: hacktoberfest-accepted

#75 Best time to buy and sell the stock #12
  January 2024/Best Time to buy and sell the stock
  January 2024/Spiral Matrix.txt
Labels: hacktoberfest-accepted

#76 Added POTD solution for 16 July.
  July 2024/Remaining_String(16 July).cpp
Labels: hacktoberfest-accepted

#78 issue #26: Add French Flashcard Learning Project
  Mini Projects/French Flash Card Project/data/french_words.csv
  Mini Projects/French Flash Card Project/data/words_to_learn.csv
  Mini Projects/French Flash Card Project/images/card_back.png
  Mini Projects/French Flash Card Project/images/card_front.png
  Mini Projects/French Flash Card Project/images/right.png
  Mini Projects/French Flash Card Project/images/wrong.png
  Mini Projects/French Flash Card Project/main.py
Labels: good first issue, hacktoberfest-accepted

#79 Create Max distance between same elements(10th October).java
  October 2024/Max distance between same elements(10th October).java
Labels: hacktoberfest-accepted

#80 Added POTD for 14 July.
  July 2024/Segregate_0s_and_1s(14 July).cpp
Labels: hacktoberfest-accepted

#82 Added Codechef Contest Problems #19
  October 2024/Codechef Contest Problems/a.exe
  October 2024/Codechef Contest Problems/chefAndParole.c++
  October 2024/Codechef Contest Problems/gcd.c++
  October 2024/Codechef Contest Problems/rectangled.c++
Labels: good first issue, hacktoberfest-accepted

#83 Added 'Square root of a number' dated 13th August 2024
  August 2024/(Square root of a number) dated 13th August 2024
Labels: hacktoberfest-accepted

#84 Added POTD solution for 2nd July.
  July 2024/Linked_list_of_strings_forms_a_palindrome(2 July).cpp
Labels: hacktoberfest-accepted

#88 Word Search Jan streek Leetcode issue #12
  January 2024/WordSearch.txt
Labels: hacktoberfest-accepted

#86 30 April 2024 problem: Add Number LinkedList in java issue #15
  April 2024/AddNumLinkedList_30April.java
Labels: good first issue, hacktoberfest-accepted

#87 6th april (Count ways to N'th Stair) : issue : #15
  April 2024/Count_ways_to_Nth_stair(6-04-2024)/Question.md
  April 2024/Count_ways_to_Nth_stair(6-04-2024)/Solution.cpp
  April 2024/readme.md
Labels: good first issue, hacktoberfest-accepted

#91 Create Max distance between same elements(10 oct).cpp
  October 2024/Max distance between same elements(10 oct).cpp
Labels: hacktoberfest-accepted

#92 Create Reorganize The Array(11th October).java
  October 2024/Reorganize The Array(11th October).java
Labels: hacktoberfest-accepted

#93 Added POTD solution for 11 September.
  September 2024/Reorganize_The_Array(11 Sept).cpp
Labels: hacktoberfest-accepted

#99 Added solution of POTD 25th of May in C++
  May 2024/You and Your Books(25 May).cpp
Labels: good first issue, hacktoberfest-accepted

#100 Text-Summarizer created and added
  Projects Ai-ML/Text Summariser/README
  Projects Ai-ML/Text Summariser/app.py
Labels: good first issue, hacktoberfest-accepted

#101 Email Reminder-added in mini project section
  Mini Projects/react-email/README.md
  Mini Projects/react-email/package-lock.json
  Mini Projects/react-email/package.json
  Mini Projects/react-email/public/favicon.ico
  Mini Projects/react-email/public/index.html
  Mini Projects/react-email/public/logo192.png
  Mini Projects/react-email/public/logo512.png
  Mini Projects/react-email/public/manifest.json
  Mini Projects/react-email/public/robots.txt
  Mini Projects/react-email/src/App.css
  Mini Projects/react-email/src/App.js
  Mini Projects/react-email/src/App.test.js
  Mini Projects/react-email/src/components/contact.css
  Mini Projects/react-email/src/components/contact.jsx
  Mini Projects/react-email/src/index.css
  Mini Projects/react-email/src/index.js
  Mini Projects/react-email/src/logo.svg
  Mini Projects/react-email/src/reportWebVitals.js
  Mini Projects/react-email/src/setupTests.js
Labels: good first issue, hacktoberfest-accepted

#104 Solution for "Geek and its Game of Coins" (29 May)
  May 2024/geekAndItsGameOfCoins.cpp
Labels: hacktoberfest-accepted

#106 Q & Ans Chatbot-added
  Mini Projects/bot/app.py
  Mini Projects/bot/gitattributes
  Mini Projects/bot/requirements.txt
Labels: hacktoberfest-accepted

#107 Create Two Smallests in Every Subarray(12th October).java
  October 2024/Two Smallests in Every Subarray(12th October).java
Labels: hacktoberfest-accepted

#108 Create Spirally traversing a matrix(1st August).java
  August 2024/Spirally traversing a matrix(1st August).java
Labels: hacktoberfest-accepted

#103 feat: added signing with google using authlib
  Mini Projects/google Signin wih Authlib/.gitignore
  Mini Projects/google Signin wih Authlib/requirements.txt
  Mini Projects/google Signin wih Authlib/server.py
  Mini Projects/google Signin wih Authlib/templates/home.html
Labels: good first issue, hacktoberfest-accepted

#114 Datawiz Project
  Mini Projects/DataWiz/LICENSE
  Mini Projects/DataWiz/README.md
  Mini Projects/DataWiz/app.png
  Mini Projects/DataWiz/app.py
  Mini Projects/DataWiz/requirements.txt
Labels: good first issue, hacktoberfest-accepted

#112 SUM OF PRODUCT (12-04-2024)
  April 2024/Sum_Of_Products(12-04-2024)/Sum_Of_Products(12-04-2024).png
  April 2024/Sum_Of_Products(12-04-2024)/Sum_Of_Products(12-04-2024).py
  April 2024/Union_Of_two_sortedarrays(20-04-2024)/Union_Of_two_sortedarrays(20-04-2024).py
  April 2024/readme.md
Labels: good first issue, hacktoberfest-accepted

#111 Create Validate an IP Address(6th August).java
  August 2024/Validate an IP Address(6th August).java
Labels: hacktoberfest-accepted

#109 Create N meetings in one room(4th August).java
  August 2024/N meetings in one room(4th August).java
Labels: hacktoberfest-accepted

#110 Create Bottom View of Binary Tree(5th August).java
  August 2024/Bottom View of Binary Tree(5th August).java
Labels: hacktoberfest-accepted

#116 Two Smallests in Every Subarray(12 oct).cpp
  October 2024/Two Smallests in Every Subarray(12 oct).cpp
Labels: hacktoberfest-accepted

#115 Language Translator added
  Mini Projects/language_Translator_multi/countries.js
  Mini Projects/language_Translator_multi/index.html
  Mini Projects/language_Translator_multi/script.js
  Mini Projects/language_Translator_multi/settings.json
  Mini Projects/language_Translator_multi/style.css
Labels: hacktoberfest-accepted

#117 Added Solution to POTD for 12 September.
  September 2024/Two_Smallests_in_Every_Subarray(12 Sept).cpp
Labels: hacktoberfest-accepted

#118 Create Delete Alternate Nodes(13th October).java
  October 2024/Delete Alternate Nodes(13th October).java
Labels: hacktoberfest-accepted

#119 Solution of Construct Binary Tree from Parent Array (17 July)
  July 2024/Construct_Binary_Tree_from_Parent_Array(17 July).cpp
Labels: good first issue, hacktoberfest-accepted

#121 Delete Alternate Nodes
  Delete Alternate Nodes( Oct13__POTD_ GFG
  October 2024/maximumPossibleNumberByBinaryConcatenation.cpp
  October 2024/maximumProduct.cpp
Labels: good first issue, hacktoberfest-accepted

#122 Create Multiply two linked lists_(1stOctPOTDgfg)
  Multiply two linked lists_(1stOctPOTDgfg)
Labels: hacktoberfest-accepted

#125 Solution Find the number of islands(6 oct POTD -GFG)
  Find the number of islands(six oct POTD -GFG)
Labels: hacktoberfest-accepted

#123 Adding Stock Price Prediction using LSTM
  Projects Ai-ML/Stock Price Prediction - LSTM/Stock_price_prediction_LSTM.py
  Projects Ai-ML/Stock Price Prediction - LSTM/TCS.csv
  Projects Ai-ML/Stock Price Prediction - LSTM/TCS_stock_output_graph_on_TEST_data.png
  Projects Ai-ML/Stock Price Prediction - LSTM/TCS_stock_output_graph_on_entire_dataset.png
  Projects Ai-ML/Stock Price Prediction - LSTM/readme.md
Labels: good first issue, hacktoberfest-accepted

#126 Create Delete Alternate Nodes(13 OCT).java
  October 2024/Delete Alternate Nodes(13 OCT).java
Labels: enhancement, hacktoberfest-accepted

#124 Solution Divisibility by 8 (28 Feb)
  February 2024/Divisibilityby8.py
Labels: good first issue, hacktoberfest-accepted

#129 adding GFG POTD 24-02-2024 Maximum Sum Problem
  February 2024/maximum_sum_problem.py
Labels: hacktoberfest-accepted

#131 Added POTD solution for 13 September
  September 2024/Delete_Alternate_Nodes(13 Sept).cpp
Labels: hacktoberfest-accepted

#133 Longest Common Prefix of Strings
  July 2024/Longest Common Prefix of Strings(july_30_POTD_gfg)
Labels: hacktoberfest-accepted

#120 Solution Odd Even Problem (01 July).java
  June 2024/GFGPOTD_01_06_2024_odd_even_problem.java
Labels: good first issue, hacktoberfest-accepted

#134 Create Spirally traversing a matrix(1stAugust_POTD_GFG)
  August 2024/Spirally traversing a matrix(1stAugust_POTD_GFG)
Labels: hacktoberfest-accepted

#136 Create Sum of all substrings of a number(1stApril_POTD_GFG)
  April 2024/Sum of all substrings of a number(1stApril_POTD_GFG)
Labels: hacktoberfest-accepted

#135 Solution Remove Half Nodes(20 July)
  July 2024/Remove Half Nodes(20 July).cpp
Labels: hacktoberfest-accepted

#137 Create Parenthesis Checker(18 sep GFG-POTD)
  Parenthesis Checker(18 sep GFG-POTD)
Labels: hacktoberfest-accepted

#139 Create Missing And Repeating(23 sep GFG-POTD)
  Missing And Repeating(23 sep GFG-POTD)
Labels: hacktoberfest-accepted

#140 Create Odd Even Problem(1st_May_POTD_gfg)
  May 2024/Odd Even Problem(1st_May_POTD_gfg)
Labels: hacktoberfest-accepted

#141 Create Majority Vote(3 oct GFG-POTD)
  Majority Vote(3 oct GFG-POTD)
Labels: hacktoberfest-accepted

#145 Added emoji Generator
  Mini Projects/emoji_generator/emoji_gen.py
  Mini Projects/emoji_generator/requirements.txt
Labels: good first issue, hacktoberfest-accepted

#144 Create Peak element(1stMarch_POTD_gfg)
  March 2024/Peak element(1stMay_POTD_gfg)
Labels: hacktoberfest-accepted

#146 Added POTD solution for 14 September.
  September 2024/Count_Linked_List_Nodes(14 Sept).cpp
Labels: hacktoberfest-accepted

#150 Advanced Stock Predictor Dashboard
  Projects Ai-ML/Advanced Stock Analysis Dashboard - ASPL/aspd.py
Labels: hacktoberfest-accepted

#151 Added 11_August_POTD.cpp
  August 2024/11_August_POTD.cpp
Labels: hacktoberfest-accepted

#152 password suggestor by vinnie
  Mini Projects/password suggestor
Labels: good first issue, hacktoberfest-accepted

#153 Create Add Number Linked Lists(30April GFG-POTD)
  April 2024/Add Number Linked Lists(30April GFG-POTD)
Labels: hacktoberfest-accepted

#127 Book_My_Show_clone
  Mini Projects/book_my_show_clone/avatar2.png
  Mini Projects/book_my_show_clone/batman.png
  Mini Projects/book_my_show_clone/bookmyshow logo.png
  Mini Projects/book_my_show_clone/bookmyshowclone1.html
  Mini Projects/book_my_show_clone/drishyam.png
  Mini Projects/book_my_show_clone/facebook.png
  Mini Projects/book_my_show_clone/instagram.png
  Mini Projects/book_my_show_clone/jawaan.png
  Mini Projects/book_my_show_clone/karnan.png
  Mini Projects/book_my_show_clone/kumbalangi.png
  Mini Projects/book_my_show_clone/linkedin.png
  Mini Projects/book_my_show_clone/master.png
  Mini Projects/book_my_show_clone/movie1.png
  Mini Projects/book_my_show_clone/movie2.png
  Mini Projects/book_my_show_clone/movie3.png
  Mini Projects/book_my_show_clone/pathaan.png
  Mini Projects/book_my_show_clone/pushpa.png
  Mini Projects/book_my_show_clone/rrr.png
  Mini Projects/book_my_show_clone/twitter.png
  Mini Projects/book_my_show_clone/working.png
  Mini Projects/book_my_show_clone/youtube.png
  Mini Projects/readme.md
Labels: hacktoberfest-accepted

#154 Create Array to BST(25 july-GFG -POTD)
  July 2024/Array to BST(25 july-GFG -POTD)
Labels: good first issue, hacktoberfest-accepted

#155 Solution does array represent heap (17 feb)
  February 2024/does array represent heap.py
Labels: hacktoberfest-accepted

#157 Solution to potd 14-10-2024 in C++
  October 2024/Count Linked List Nodes(October 14).cpp
Labels: hacktoberfest-accepted

#158 Create ZigZag Tree Traversal(21march GFG-POTD)
  March 2024/ZigZag Tree Traversal(21march GFG-POTD)
Labels: hacktoberfest-accepted

#159 Create Root to Leaf Paths (8 May GFG-POTD)
  May 2024/Root to Leaf Paths  (8 May GFG-POTD)
Labels: hacktoberfest-accepted

#156 Added GeeksForGeeks Problem of the Day for 14 OCT 2024
  October 2024/Count_Linked_List_Nodes_14_10_24.cpp
Labels: good first issue, hacktoberfest-accepted

#162 Adding Party_of_couples(10-04-24)
  April 2024/Party_Of_Couples(10-04-2024)/Question.md
  April 2024/Party_Of_Couples(10-04-2024)/Solution.cpp
Labels: hacktoberfest-accepted

#161 Diabetes Prediction System
  Projects Ai-ML/Diabetes Prediction System/Deploying_Machine_Learning_model_using_Streamlit.ipynb
  Projects Ai-ML/Diabetes Prediction System/Diabetes_Prediction_Web_App.py
  Projects Ai-ML/Diabetes Prediction System/diabetes.csv
  Projects Ai-ML/Diabetes Prediction System/requirements.txt
  Projects Ai-ML/Diabetes Prediction System/trained_model.sav
Labels: hacktoberfest-accepted

#165 Create Subarray range with given sum(15 oct).java
  October 2024/Subarray range with given sum(15 oct).java
Labels: hacktoberfest-accepted

#167 Add Expense Tracker with Pie Chart Visualization (#26)
  Mini Projects/Expense_tracker/Expenses.py
  Mini Projects/Expense_tracker/README.md
  Mini Projects/Expense_tracker/expenses.json
Labels: good first issue, hacktoberfest-accepted

#168 Print matrix in diagonal pattern
  March 2024/Print_matrix_in_diagonal_pattern.java
Labels: good first issue, hacktoberfest-accepted

#171 Create Fibonacci_series_up_to_Nth_term(23_March).py
  March 2024/Fibonacci_series_up_to_Nth_term(23_March).py
Labels: good first issue, hacktoberfest-accepted

#173 Create POTD-GFG-Minimum element in BST.cpp
  March 2024/POTD-GFG-Minimum element in BST.cpp
Labels: good first issue, hacktoberfest-accepted

#175 Create Compare_two_fraction(21_june_2024).py
  June 2024/Compare_two_fraction(21_june_2024).py
Labels: hacktoberfest-accepted

#176 Added POTD Solution of august_3
  August 2024/celebrity_problem_3_august.cpp
Labels: good first issue, hacktoberfest-accepted

#177 Remove K Digits
  January 2024/Remove_K_Digits.java
Labels: hacktoberfest-accepted

#179 Created Paths from root with a specified sum.cpp
  January 2024/Paths from root with a specified sum.cpp
Labels: hacktoberfest-accepted

#184 Two Swaps(16 Oct).cpp
  October 2024/Two Swaps(16 Oct).cpp
Labels: hacktoberfest-accepted

#183 Create Left View of Binary Tree.cpp
  August 2024/Left View of Binary Tree.cpp
Labels: hacktoberfest-accepted

#182 Maximum_Difference
  August 2024/Maximum_Difference.java
Labels: hacktoberfest-accepted

#180 Count Linked List Nodes Oct-14
  October 2024/Count Linked List Nodes(October 14).py
Labels: good first issue, hacktoberfest-accepted

#185 Additive_sequence
  March 2024/Additive_sequence.java
Labels: hacktoberfest-accepted

#188 Create Remove every k'th node(29 APR GFG-POTD)
  April 2024/Remove every k'th node(29 APR GFG-POTD)
Labels: good first issue, hacktoberfest-accepted

#190 Create N-queen-problem.cpp
  August 2024/N-queen-problem.cpp
Labels: hacktoberfest-accepted

#192 DivisorGame May 9th
  May 2024/DivisorGame( May_9_2024).py
Labels: good first issue, hacktoberfest-accepted

#196 Create Insert_an_Element_at_the_Bottom_of_a_Stack(24_march_2024).py
  March 2024/Insert_an_Element_at_the_Bottom_of_a_Stack.py
Labels: hacktoberfest-accepted

#197 Swap_the_array_elements(4_march_2024).py
  March 2024/Insert_an_Element _at_the_Bottom_of_a_Stack(4_march_2024).py
Labels: hacktoberfest-accepted

#187 Created the code file
  October 2024/Two_swaps(16th October).cpp
Labels: good first issue, hacktoberfest-accepted

#202 Add files via upload
  April 2024/count_ele.cpp
Labels: hacktoberfest-accepted

#203 Code for Closest_Three_Sum.cpp
  July 2024/Closest_Three_Sum.cpp
Labels: hacktoberfest-accepted

#205 Create Number_of_Rectangles_in_a_Circle.cpp
  June 2024/Number_of_Rectangles_in_a_Circle.cpp
Labels: hacktoberfest-accepted

#206 Code for Boolean_Parenthesization in cpp
  February 2024/Boolean_Parenthesization.cpp
Labels: hacktoberfest-accepted

#207 Create LargestSwap.cpp (POTD: 15th July)
  July 2024/LargestSwap.cpp
Labels: good first issue, hacktoberfest-accepted

#208 added solution for POTD 17 September.
  September 2024/Split_Linked_List_Alternatingly(17 Sept).cpp
Labels: hacktoberfest-accepted

#209 Create Reverse First K elements of Queue(12 JAN GFG POTD)
  January 2024/Reverse First K elements of Queue(12 JAN  GFG POTD)
Labels: hacktoberfest-accepted

#210 Create Course Schedule(23 jan GFG-POTD)
  January 2024/Course Schedule(23 jan GFG-POTD)
Labels: good first issue, hacktoberfest-accepted

#212 Create Split Linked List Alternatingly gfg potd 17 oct 24
  October 2024/Split Linked List Alternatingly     gfg potd 17 oct 24
Labels: good first issue, hacktoberfest-accepted

#213 Create odd even problems gfg june
  June 2024/odd even problems.cpp
Labels: hacktoberfest-accepted

#217 Added POTD for 18 September.
  September 2024/Single_Number(18 Sept).cpp
Labels: hacktoberfest-accepted

#220 Create 8_july_gfg_ Search in Rotated Sorted Array_POTD
  July 2024/8_july_gfg_  Search in Rotated Sorted Array_POTD
Labels: good first issue, hacktoberfest-accepted

#221 Create Arrange Consonants and Vowels_1MAY_GFG_POTD
  May 2024/Arrange Consonants and Vowels_1MAY_GFG_POTD
Labels: good first issue, hacktoberfest-accepted

#225 Create Hotel Management System.py
  Mini Projects/Hotel Management System/Hotel Management System.py
  Mini Projects/Hotel Management System/Screenshot 2024-10-18 212642.png
  Mini Projects/Hotel Management System/Screenshot 2024-10-18 213410.png
  Mini Projects/Hotel Management System/Screenshot 2024-10-18 213457.png
Labels: good first issue, hacktoberfest-accepted

#230 Create Minimum steps to destination(12 May GFG POTD).cpp
  May 2024/Minimum steps to destination(12 May GFG POTD).cpp
Labels: hacktoberfest-accepted

#231 Create Minimum element in BST.cpp
  March 2024/Minimum element in BST.cpp
Labels: good first issue, hacktoberfest-accepted

#234 Create htmlForm.html
  Mini Projects/htmlForm.html
Labels: good first issue, hacktoberfest-accepted

#239 single among triplet jan 4th solution
  January 2024/singleamongtriplets.py
Labels: good first issue, hacktoberfest-accepted

#240 game with string feb 19th
  February 2024/gamewithstring.py
Labels: hacktoberfest-accepted

#241 Trained and Made a gradio interface
  Projects Ai-ML/Medical_insurence_With_gradio_interface-2.ipynb
Labels: good first issue, hacktoberfest-accepted

#242 Create Recamans sequence( FEB_POTD_GFG_2024)
  February 2024/Recamans sequence( FEB_POTD_GFG_2024)
Labels: hacktoberfest-accepted

#243 Create Sum of all substrings of a number(4th_April_GFG_POTD)
  April 2024/Sum of all substrings of a number(4th_April_GFG_POTD)
Labels: hacktoberfest-accepted

#246 Create nearest_multiple_of_10.py
  October 2024/nearest_multiple_of_10.py
Labels: hacktoberfest-accepted

#248 Feb 27 2024 Play with OR
  February 2024/Play With OR Feb 27 2024.cpp
Labels: hacktoberfest-accepted

#252 Create Find missing in second array(19 APRIL GFG POTD).CPP
  April 2024/Find missing in second array(19 APRIL GFG POTD).CPP
Labels: hacktoberfest-accepted

#253 30th june
  June 2024/deletion dll.py
Labels: hacktoberfest-accepted

#254 Create K distance from root( 3 MAY GFG POTD).cpp
  May 2024/K distance from root( 3 MAY GFG POTD).cpp
Labels: hacktoberfest-accepted

#257 inserting at the bottom of the stack
  March 2024/insertatbottom(24thmarch).cpp
  March 2024/readme2.md
Labels: hacktoberfest-accepted

#258 Create Maximum occurred integer.py June 7 2024
  June 2024/Maximum occurred integer.py
Labels: hacktoberfest-accepted

#261 Create Longest subsequence-1( 27 MAY GFG POTD)
  May 2024/Longest subsequence-1( 27 MAY GFG POTD)
Labels: good first issue, hacktoberfest-accepted

#264 Create Find the Sum of Last N nodes of the Linked List(23 oct GFG POT…
  October 2024/Find the Sum of Last N nodes of the Linked List(23 oct GFG POTD).cpp
Labels: hacktoberfest-accepted
